server:
  port: 8082

spring:
  application:
    name: auth-app-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  security:
    oauth2:
      client:
        registration:

          google:
            client-id: ${GOOGLE_CLIENT_ID:your-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-client-secret}
            scope:
              - email
              - profile
              - openid

          github:
            client-id: ${GITHUB_CLIENT_ID:your-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:your-client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - user:email
              - read:user

    jwt:
      secret: ${JWT_SECRET:your-secret}
      issuer: ${JWT_ISSUER:api.substring.com}
      access-tls-seconds: ${ACCESS_TLS_SECONDS:3600}
      refresh-tls-seconds: ${REFRESH_TLS_SECONDS:86400}
      refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
      cookie-secure: ${JWT_COOKIE_SECURE:true}
      cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
      cookie-same-site: ${JWT_COOKIE_SITE_ONLY:None}
      cookie-domain: ${JWT_COOKIE_DOMAIN:}

logging:
  level:
    org.springframework.web: DEBUG

app:
  cors:
    front-end-url: ${FRONT_END_URL:https://auth-app-spring.vercel.app}

  auth:
    frontend:
      success-redirect: ${FRONT_END_SUCCESS_REDIRECT:https://auth-app-spring.vercel.app/oauth/success}
      failure-redirect: ${FRONT_END_FAILURE_REDIRECT:https://auth-app-spring.vercel.app/oauth/failure}



cloudinary:
     cloud-name: ${CLOUD_NAME}
     api-key: ${CLOUD_API_KEY}
     api-secret: ${CLOUD_SECRET}
